import Head from 'next/head';
import Header from '@/components/layout/Header';

export default function Index() {
  return (
    <div>
      <Head>
        <title>Food Ordering</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='@/public/favicon.ico'/>
      </Head>
      <Header />
    </div>
  )
}
