import Head from "next/head";
import Home from "./home";

export default function Index() {
  return (
    <div>
      <Head>
        <title>Food Ordering</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="@/public/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
          integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer"
        />
      </Head>
      <Home />
    </div>
  );
}
